### ISSUE TITLE
No longer scanning full words in Google Docs

### ISSUE THREAD

**Issue by LadyLyndis** [FooSoft/yomichan#179]
Up until yesterday I could use Yomichan to scan full words in a Google Docs document. Today, however, it only wants to scan one character at a time, which isn't helpful at all. It happens even after a browser restart. It seems to be working as normal on other sites, including Google Sheets.

**Comment by siikamiika** [comment]
Do you have an example document with this problem? I can't reproduce on Chrome or Firefox
![2019-08-13_19-55-22](https://user-images.githubusercontent.com/5602483/62960979-87436b80-be04-11e9-99e1-8e0722c22e47.png)

**Comment by LadyLyndis** [comment]
Sure, here's an example doc: [this one](https://docs.google.com/document/d/1GvxFCXYpAFte9_qEwg2fCfFP0HvX68Dee3RmHAR2MAU/edit?usp=sharing) 

I've attached a screenshot.
![Annotation 2019-08-13 142520](https://user-images.githubusercontent.com/30663715/62967274-a2978200-bdd6-11e9-9ecd-33a87f7b4594.png)

**Comment by Ceiyne** [comment]
I noticed this happening today and was coming here to open an issue when I saw that someone beat me to it.  It happens for me on all Google Docs, including the sample that LadyLyndis shared above.

**Comment by siikamiika** [comment]
Your example doc works for me, so we are probably seeing a different version of Google Docs.

Does this also happen if you open the document without logging in to your Google account (for example by opening it in incognito or a new profile if you don't mind reinstalling Yomichan)? You might have to allow Yomichan to run in incognito separately from extension settings.

If it does and you are sure there's no private information on the page, it would help if you saved the version of the page you're seeing with ctrl+s or cmd+s, zipped it, including both the html page and the directory named `Web Page Title_files` and shared it in this thread.

**Comment by Ceiyne** [comment]
I created my own test document to try it out in Incognito mode, without signing in.  Unfortunately, the problem is still there.  I've zipped up the html and associated files as you requested.

[Yomichan test.zip](https://github.com/FooSoft/yomichan/files/3502569/Yomichan.test.zip)

Here's a link to the document in case you need it, although it seems like the issue isn't document-specific at this point: 

https://docs.google.com/document/d/1BjS0hMMFt2FgfANSzOMtmJEhmFmqGRhBZZIaB5a-J-o/edit

**Comment by siikamiika** [comment]
@Ceiyne Thanks a lot! The document seems to have [these characters](https://en.wikipedia.org/wiki/Zero-width_non-joiner) between the Japanese characters for some reason:
![2019-08-14_21-48-13](https://user-images.githubusercontent.com/5602483/63047538-54b97180-bedd-11e9-8641-d183c47b3e58.png)
I was able to fix the issue by filtering those characters out before getting the scanned range as text, but that caused issues with text selection because the filtered string length didn't match with the one on the page. Seems like a reasonable tradeoff unless this becomes more common.

**Comment by siikamiika** [comment]
I have created a pull request fixing this issue, and also added a fix for the text selection length. I noticed while testing that because each ZWNJ character takes up one space, 10 characters might not be long enough for scanning. 目\&zwnj;を\&zwnj覚\&zwnjま\&zwnjし\&zwnjた is actually 11 characters and isn't detected as the past tense without increasing the scanning length first. I might fix it later.

**Comment by siikamiika** [comment]
It's fixed now

**Comment by Ceiyne** [comment]
Thanks so much for working on this so quickly!  I have a couple of questions, though.

1. I restarted Chrome and also re-opened my Google Doc but I still have the problem.  Is there something I need to do manually to get the new version of the plugin?  The extensions page shows I have Yomichan v1.5.2.

2. Do you think this could be some kind of bug in Docs?  I wasn't familiar with ZWNJ characters before this, but from what I read about them, it doesn't sound like something that should be present in between every character in every document.

3. I'm sorry to bother you with this, too, but would it be possible for you to look at issue #148 as well?  I opened it last year but no one ever responded to it.

**Comment by siikamiika** [comment]
1. The fix is currently only in my fork of Yomichan, so it's not trivial to get it up and running and you could lose your settings or dictionaries when installing it. If you want to take the risk,
    - `git clone https://github.com/siikamiika/yomichan`
    - `cd yomichan`
    - `git checkout fix-zwnj`
    - open `chrome://extensions/` in Chrome
    - enable developer mode
    - click "Load unpacked"
    - go to `yomichan/ext/` in the file browser and click Open
    - configure Yomichan if it loaded as a separate extension, otherwise it's ready to use
2. It's a bug in either Docs or Chrome 76, because it also started happening to me after updating Chrome to the newest version (I had 75 previously). There could be some conditional stuff in the Docs code for specific Chrome versions. I don't know much about the character either, but seems like it's not supposed to be used with Japanese text.
3. I'm not very familiar with the code related to this area of scanning (input fields like `<textarea>` and `<input>`). If I remember correctly, there's a fundamental limitation in browsers and the workaround for this in Yomichan is to create an invisible element containing the same text as the input field, place it on top of the input field and scan text from that instead. It's probably not copying some styles from the input field correctly, but anyway it seems like a hard problem to fix (at least for me). As a workaround you could reprogram your brain to scan the text a bit above and add more offset in Yomichan settings so that you can see the context.

**Comment by Ceiyne** [comment]
Thanks for the info.  For question 1, do you know when the fix might be rolled into a full release of Yomichan that could be installed normally?  If it won't be too long I would probably just wait.

**Comment by FooSoft** [comment]
I've been really bad about promoting changes to mainline. I've been planning to do it for about two weeks now, but have been super busy with IRL things. I should be able to push all of this to main this weekend (most of the other changes have been getting hammered on in Yomichan testing).

**Comment by Ceiyne** [comment]
Thanks!

**Comment by LadyLyndis** [comment]
Thank you so much! It updated for me and now it works perfectly again. I really appreciate y'all's prompt response to this, it's a huge help!
