### ISSUE TITLE
Dictionary error on Firefox Nightly

### ISSUE THREAD

**Issue by SimonPilkington** [FooSoft/yomichan#588]
Yomichan is currently unusable on Firefox nightly. Both testing and stable versions are affected. Listing dictionaries fails with this error:
```
Yomichan v20.5.22.0 has encountered a problem.
Originating URL: moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/bg/settings.html
Error: Unexpected response of type undefined ({"action":"getDictionaryInfo","params":{}})
_apiInvoke/</<@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/js/api.js:295:28
Async*_apiInvoke/<@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/js/api.js:285:28
_apiInvoke@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/js/api.js:283:12
apiGetDictionaryInfo@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/js/api.js:128:12
onDatabaseUpdated@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/bg/js/settings/dictionaries.js:434:36
dictSettingsInitialize@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/bg/js/settings/dictionaries.js:415:11
async*onReady@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/bg/js/settings/main.js:318:11
async*@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/bg/js/settings/main.js:328:25
j@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:29999
g/</k<@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:30313
setTimeout handler*g/<@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:30522
i@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:28017
fireWith@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:28783
fire@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:28819
i@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:28017
fireWith@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:28783
ready@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:31934
S@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:3:35
EventListener.handleEvent*@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:3:149
@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:220
@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:225
```
Importing a dictionary also fails:
```
Originating URL: moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/bg/settings.html
Error: Timeout
_apiInvokeWithProgress/</timer<@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/js/api.js:261:20
setTimeout handler*_apiInvokeWithProgress/<@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/js/api.js:259:17
_apiInvokeWithProgress@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/js/api.js:206:12
apiImportDictionaryArchive@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/js/api.js:152:12
onDictionaryImport@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/bg/js/settings/dictionaries.js:683:44
async*dictSettingsInitialize@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/bg/js/settings/dictionaries.js:410:42
onReady@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/bg/js/settings/main.js:318:11
async*@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/bg/js/settings/main.js:328:25
j@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:29999
g/</k<@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:30313
setTimeout handler*g/<@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:30522
i@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:28017
fireWith@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:28783
fire@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:28819
i@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:28017
fireWith@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:28783
ready@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:31934
S@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:3:35
EventListener.handleEvent*@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:3:149
@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:220
@moz-extension://9699283a-4027-4ce4-81ec-26949dd5755a/mixed/lib/jquery.min.js:2:225
```

**Comment by SimonPilkington** [comment]
The offending commit is 51e17b35e3a855c0db6c4be94a8cb416b14c8ad7.

**Comment by siikamiika** [comment]
I can confirm this on Nightly 79 (Windows). Firefox 77 on Windows and Linux works. Extension messaging is broken while Yomichan Options page is open, but closing the page makes messaging work again.

**Comment by siikamiika** [comment]
Marked this as a browser bug for now. Could be worth it to report to Mozilla although they mention that Nightly can be unstable.

> The offending commit is [51e17b3](https://github.com/FooSoft/yomichan/commit/51e17b35e3a855c0db6c4be94a8cb416b14c8ad7).

I can reproduce the issue on 51e17b35e3a855c0db6c4be94a8cb416b14c8ad7 parent commit too.

**Comment by SimonPilkington** [comment]
Dictionaries are definitely broken on 51e17b35e3a855c0db6c4be94a8cb416b14c8ad7 but not on 3c48290cd83744983df2e708b892a8415bcf750f for me. I'm on Linux, but I don't know how that could be related. #589 is broken on both however.

**Comment by toasted-nutbread** [comment]
The timeout issue should be fixed with #587. [I made a hotfix tag for this](https://github.com/FooSoft/yomichan/issues/586#issuecomment-636539693) ([20.5.22.1](https://github.com/FooSoft/yomichan/commits/20.5.22.1)), but @FooSoft is in charge of releasing.

**Comment by FooSoft** [comment]
Fixed push out -- apologies for the delay!

**Comment by SimonPilkington** [comment]
#587 does not fix importing on Nightly. I have reported this and #589 to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1643649

**Comment by toasted-nutbread** [comment]
> #587 does not fix importing on Nightly. I have reported this and #589 to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1643649

Added a comment and example extension with the issue.
https://github.com/toasted-nutbread/firefox-web-extension-send-message-bug

@SimonPilkington I'm not sure what exactly your scenario is for using Yomichan on Nightly, but Firefox Developer Edition (currently) doesn't have this problem. You could consider using that instead, as it's usually more stable.

**Comment by SimonPilkington** [comment]
Thank you. That helps.

I don't have any particular reason. I just enjoy using bleeding-edge software and don't mind occasionally encountering issues. Nightly is not especially unstable. This is the first serious issue I've encountered in the last six months or more. I am currently working around this by building from 3c48290cd83744983df2e708b892a8415bcf750f.

**Comment by SimonPilkington** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1642967 appears to have fixed importing dictionaries, however enumerating them still fails for me. Can you confirm?

**Comment by toasted-nutbread** [comment]
I am seeing some intermittent issues with the database request failing, yes. Unclear why it is happening, but the `indexedDB.getAll` call seems to be closing the extension message connection early.

**Comment by SimonPilkington** [comment]
Seems to have been fixed by unknown other Firefox bug in the meantime.
