### ISSUE TITLE
Bug: pop-up by only hovering

### ISSUE THREAD

**Issue by Knobibrot** [FooSoft/yomichan#982]
Every once in a while, yomichan starts showing me the pop-ups by just hovering over Japanese text, without holding shift. The last two times this happened I couldn't figure out how to fix this other than re-installing the add-on. It happened again Just now, after restarting my browser (chrome) and restoring the session. This time I tried reseting yomichan's default settings and the problem went away. I still don't know how to reproduce the bug, sorry. I also didn't think to backup the settings before trying it, so I can't upload them (this time) in case the issue is caused by some invalid settings.

Both chrome and yomichan are up to date and I'm running win 10.

**Comment by toasted-nutbread** [comment]
This is a bug in the current version, where new installations incorrectly upgrade settings, which includes incorrectly assigning the search key. A new release should be coming out soon which fixes this.

To work around this for now, you may have to do the following:
1. Install Yomichan (don't need to re-install if it's already installed)
2. Open the settings page and edit any setting (so that the settings are saved)
3. Close the browser (all tabs/windows)
4. Open the browser (this will corrupt the settings by performing an incorrect upgrade, but shouldn't need to do future upgrades)
5. Open the settings page (so that the settings are saved)
6. Everything should work now, since erroneous upgrades should not be performed anymore.

#962

**Comment by toasted-nutbread** [comment]
Based on your comment, it looks like you got it fixed by doing basically the steps I listed, albeit maybe not intentionally. I think the bug also messed up another setting, audio volume and maybe something else, so if you run into any other issues, that may be the issue.

**Comment by ThatEpicDude** [comment]
I am having the same issue. The suggested steps did not fix it for me.
It's not that big a deal if it will be addressed in a future update though.
